### ISSUE TITLE
Chat overlaps bloqs on Noodle Extensions maps

### ISSUE THREAD

**Issue by Parapass** [denpadokei/EnhancedStreamChat-v3#12]
![20220720100910_1](https://user-images.githubusercontent.com/59424861/180249519-653a7b2b-5193-43f3-983e-6e9bad67e163.jpg)
Not sure if this is intentional or not, so I'm just gonna report it here.

**Comment by denpadokei** [comment]
Thanks for the report.
What is the bsr key of the song?

**Comment by Parapass** [comment]
https://beatsaver.com/maps/15d34

**Comment by denpadokei** [comment]
To make the chat easier to read, the background transparency is 255 by default.
In that case, as shown in the image, all objects behind are erased and only light is depicted.

To get around this, the background transparency must be reduced to about half, which requires editing the json directly.

```
original
{
    "BackgroundColor": "#4C4C4CFF"
}

half
{
    "BackgroundColor": "#4C4C4CAA"
}
```

![image](https://user-images.githubusercontent.com/55026301/180436101-58216ca0-6c39-413b-ad1d-68ac8fa30bac.png)

However, it may be difficult to read the chat as the background lights show through.
