### ISSUE TITLE
Chat stops sending through messages

### ISSUE THREAD

**Issue by SyncBS** [denpadokei/EnhancedStreamChat-v3#14]
Issue:
At Random chat stops sending the messages from twitch chat, unsure if it's due to Enhanced Stream Chat or CatCore.

ESC Version: 5.0.4

[2022.08.29.16.46.28.log](https://github.com/denpadokei/EnhancedStreamChat-v3/files/9448099/2022.08.29.16.46.28.log)

**Comment by denpadokei** [comment]
The phenomenon that chat reception stops is a CatCore bug.
When the phenomenon occurs, not only ESC but also other Mods stop receiving.
Since this issue cannot be resolved with ESC, I am implementing a reconnect button in the login tab.

**Comment by SyncBS** [comment]
That was what I thought when seeing the reconnect button in the login tab, thank you for letting me know. 
I will talk with Eris about the problem in CatCore.
